/** Machine-readable deny reasons returned by the policy engine and API. */
export const POLICY_DENIED_TOKEN_NOT_ALLOWED = "POLICY_DENIED_TOKEN_NOT_ALLOWED";
export const POLICY_DENIED_WALLET_NOT_ALLOWED = "POLICY_DENIED_WALLET_NOT_ALLOWED";
export const POLICY_DENIED_EXCEEDS_PER_TX = "POLICY_DENIED_EXCEEDS_PER_TX";
export const POLICY_DENIED_EXCEEDS_DAILY = "POLICY_DENIED_EXCEEDS_DAILY";
export const POLICY_DENIED_RATE_LIMIT = "POLICY_DENIED_RATE_LIMIT";
export const POLICY_DENIED_APPROVAL_REQUIRED = "POLICY_DENIED_APPROVAL_REQUIRED";
export const POLICY_DENIED_PRICE_UNAVAILABLE = "POLICY_DENIED_PRICE_UNAVAILABLE";
export const POLICY_DENIED_AMOUNT_UNKNOWN = "POLICY_DENIED_AMOUNT_UNKNOWN";
export const POLICY_DENIED_NO_ACTIVE_POLICY = "POLICY_DENIED_NO_ACTIVE_POLICY";
export const ACTION_NOT_ALLOWED = "ACTION_NOT_ALLOWED";

export const POLICY_REASON_CODES = [
  POLICY_DENIED_TOKEN_NOT_ALLOWED,
  POLICY_DENIED_WALLET_NOT_ALLOWED,
  POLICY_DENIED_EXCEEDS_PER_TX,
  POLICY_DENIED_EXCEEDS_DAILY,
  POLICY_DENIED_RATE_LIMIT,
  POLICY_DENIED_APPROVAL_REQUIRED,
  POLICY_DENIED_PRICE_UNAVAILABLE,
  POLICY_DENIED_AMOUNT_UNKNOWN,
  POLICY_DENIED_NO_ACTIVE_POLICY,
  ACTION_NOT_ALLOWED,
] as const;

export type PolicyReasonCode = (typeof POLICY_REASON_CODES)[number];

export const INVALID_POLICY_RULE = "INVALID_POLICY_RULE";

export interface PolicyValidationIssue {
  code: typeof INVALID_POLICY_RULE;
  path: string;
  message: string;
}
